Added card placeholder
LunarTides/Hearthstone.js pull request #243
Opened 2023-08-16 07:51 UTC by IsakSkole123

Reworked the placeholder system
Changed detail mode to be a toggle

2023-08-16 08:13 UTC, IsakSkole123 commented
Test this.

2023-08-18 11:51 UTC, LunarTides requested changes

2023-08-18 11:51 UTC, LunarTides commented on src/interact.js
> +     * @param {number} [_depth=0] - The depth of recursion.
Remove the `-`

2023-08-18 12:32 UTC, LunarTides approved these changes

2023-08-18 12:34 UTC, merged